name = "auth-template"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[vars]
JWT_SECRET = "00000002000000000000502e66403313c47b53480a6993b0ebfad1ff"
JWT_EXPIRATION_DAYS = "5"
SENDER_EMAIL = "noreply@updates.isadev.icu"

# Base de datos D1 - Reemplaza TU_DATABASE_ID después de ejecutar: wrangler d1 create auth-db
[[d1_databases]]
binding = "DB"
database_name = "auth-db"
database_id = "80619adb-aa1f-413e-ba94-c538c7c167b9"

# Para desarrollo local
# [env.dev]
# ...
